import { getSession } from 'next-auth/react'
import Head from 'next/head'
import Feed from '../components/Feed'
import Header from '../components/Header'
import { Login } from '../components/Login'
import RightSideBar from '../components/RightSideBar'
import SideBar from '../components/SideBar'

export default function Home({session}) {
  if (!session) {
    return <Login />
  }
  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className='flex bg-gray-100'>
        {/* Left Sidebar */}
        <SideBar/>
        {/* Feed (Create Posts) */}
        <Feed/>
        {/* Right Sidebar */}
        <RightSideBar/>
      </main>

    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {session},
  };
}